INSERT INTO misc.HAward(title, country) VALUES ('Argentine Academy of Cinematography Arts and Sciences HAward', 10);
INSERT INTO misc.HAward(title, country) VALUES ('Argentine Film Critics Association HAward', 10);
INSERT INTO misc.HAward(title, country) VALUES ('Clarín HAward', 10);
INSERT INTO misc.HAward(title, country) VALUES ('Konex HAward', 10);
INSERT INTO misc.HAward(title, country) VALUES ('Australian Film Critics Association', 13);
INSERT INTO misc.HAward(title, country) VALUES ('Film Critics Circle of Australia', 13);
INSERT INTO misc.HAward(title, country) VALUES ('National Film HAward', 18);
INSERT INTO misc.HAward(title, country) VALUES ('Meril Prothom Alo HAward', 18);
INSERT INTO misc.HAward(title, country) VALUES ('Belgian Film Critics Association', 21);
INSERT INTO misc.HAward(title, country) VALUES ('Festival de Gramado', 30);
INSERT INTO misc.HAward(title, country) VALUES ('Troféu Vento norte', 30);
INSERT INTO misc.HAward(title, country) VALUES ('German Film Critics Association Awards', 80);